name: _error
timestamp: 1511198868
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1502553408
positions:
  request-quote: 'Request Quote'
sections:
  header: Header
  navigation: Navigation
  sidebar: Sidebar
  mainbar: Mainbar
  abovefooter: Abovefooter
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-6091: 'System Messages'
  content:
    system-content-3910: 'Page Content'
  custom:
    custom-5592: 'Custom HTML'
    custom-2850: 'Custom HTML'
    custom-4853: 'Header Contact'
    custom-2644: 'Custom HTML'
    custom-7629: 'About Us'
    custom-5843: Navigation
    custom-2613: 'Footer Menu'
  social:
    social-2712: Social
  logo:
    logo-8609: Logo
  menu:
    menu-8939: Menu
  position:
    position-position-2267: 'Request Quote'
  branding:
    branding-4429: Branding
  mobile-menu:
    mobile-menu-6492: 'Mobile Menu'
inherit:
  default:
    header: header
    navigation: navigation
    abovefooter: abovefooter
    footer: footer
    offcanvas: offcanvas
    custom-4853: custom-9052
    social-2712: social-9497
    custom-2644: custom-2198
    logo-8609: logo-6337
    menu-8939: menu-4515
    custom-7629: custom-8680
    custom-5843: custom-6146
    position-position-2267: position-position-2582
    branding-4429: branding-4375
    custom-2613: custom-3265
    mobile-menu-6492: mobile-menu-5956
